version: "3.9"

services:
  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_DATABASE: questionsdb
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: pass # required
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "3306:3306"
    volumes:
      - questions_db:/var/lib/mysql

volumes:
  questions_db:
